const Theme = {
  color: {
    white: '#FFFFFF',
    //orange: '#EB7917',
    primary: '#5ABD8C',
    secondary: '#AFDFC7',
    blue: '#61A4EA',
    grey: '#C4C2C2',
    greyText: '#414348',
    //cyne: theme.color.cyne,
    cyne: '#21d2cc',
    inActive: '#BCCCE3',
    skyblue: '#56CAFB',
    redish: '#F28A8A',
    appBackgroundColor: '#FFFFFF',
  },
  fontFamily: {
    SFProRoundedBold: 'SF-Pro-Rounded-Bold',
    SFProRoundedLight: 'SF-Pro-Rounded-Light',
    SFProRoundedMedium: 'SF-Pro-Rounded-Medium',
    SFProRoundedRegular: 'SF-Pro-Rounded-Regular',
    SFProTextLight: 'SF-Pro-Text-Light',
    SFProTextMedium: 'SF-Pro-Text-Medium',
    SFProTextRegular: 'SF-Pro-Text-Regular',
    SFProTextSemibold: 'SF-Pro-Text-Semibold',
    SFProTextBold: 'SF-Pro-Text-Bold',
  },
  fontSize: {
    large: 45,
    title: 22,
    header: 20,
    medium: 18,
    normal: 16 + 1,
    normalSmall: 14 + 1,
    small: 12 + 1,
    exSmall: 10 + 1,
  },
};

// 'SegoeUI-Semibold',
//   'SegoeUI-Semilight',
//   'SegoeUI-BoldItalic',
//   SegoeUIBlack,
//   'SegoeUI-SemiboldItalic',
//   'SegoeUI-Italic',
//   'SegoeUIBlack-Italic',
//   'SegoeUI-LightItalic',
//   'SegoeUI-Bold',
//   SegoeUI,
//   'SegoeUI-Light',
//   'SegoeUI-SemilightItalic';
export default Theme;
